version: '3'
services:
  seevechain:
    image: node:12
    container_name: seevechain
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "1337:1337"
    environment:
      - NODE_URL=http://thor-node:8669
      - DATABASE_URL=postgresql://user:password@postgres/seevechain
      - PORT=1337
      - TIME_DIFFERENCE=0
      - NODE_ENV=development
      - DISABLE_MISSING_BLOCK_SYNC=true
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:14
    ports:
      - '5432:5432'
    command:
      [
        "postgres",
        "-cshared_preload_libraries=pg_stat_statements",
        "-cmax_connections=200"
      ]
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: seevechain
      PGDATA: "/var/lib/postgresql/data"
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d seevechain"]
      interval: 5s
      timeout: 5s
      retries: 5
